version: "3"
services:
  todo-back:
    build:
      context: ./todo-back
      target: final
      dockerfile: Dockerfile.dev
    ports:
      - 3010:3010
    environment:
      TODO_SERVER_ADDRESS: ":3010"
      TODO_SERVER_MAX_CONNECTION_AGE: 300
      TODO_SERVER_MAX_CONNECTION_IDLE: 300
      TODO_PASSWORD_HASH_SECRET: "local_password_hash"
      MONGO_DB_URI: "mongodb://root:password@mongo:27017/admin"
      TODO_MONGO_DB_NAME: "todo"
      TODO_CLOUDFLARE_ACCOUNT_ID: $TODO_CLOUDFLARE_ACCOUNT_ID
      TODO_SESSION_SECRET_KEY: "local_session_secret_key"
      TODO_SESSION_DURATION: "60"
      TODO_SESSION_NAMESPACE_IDENTIFIER: $TODO_SESSION_NAMESPACE_IDENTIFIER
      TODO_SESSION_KV_ACCESS_TOKEN: $TODO_SESSION_KV_ACCESS_TOKEN

    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: todo
    volumes:
      - ./local_data/mongodb_data:/data/db
      - ./local/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | /bin/mongosh mongo:27017/test --quiet
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 10s
    command: mongod
    # ports: 
      # - 27017:27017
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      mongo:
          condition: service_healthy
