// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: authentication/authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserSignUpStatus int32

const (
	UserSignUpStatus_SignupSignUpStatusUnknown      UserSignUpStatus = 0
	UserSignUpStatus_SignupSignUpStatusAllowed      UserSignUpStatus = 1
	UserSignUpStatus_SignupSignUpStatusWaitForAllow UserSignUpStatus = 2
	UserSignUpStatus_SignupSignUpStatusDenied       UserSignUpStatus = 3
)

// Enum value maps for UserSignUpStatus.
var (
	UserSignUpStatus_name = map[int32]string{
		0: "SignupSignUpStatusUnknown",
		1: "SignupSignUpStatusAllowed",
		2: "SignupSignUpStatusWaitForAllow",
		3: "SignupSignUpStatusDenied",
	}
	UserSignUpStatus_value = map[string]int32{
		"SignupSignUpStatusUnknown":      0,
		"SignupSignUpStatusAllowed":      1,
		"SignupSignUpStatusWaitForAllow": 2,
		"SignupSignUpStatusDenied":       3,
	}
)

func (x UserSignUpStatus) Enum() *UserSignUpStatus {
	p := new(UserSignUpStatus)
	*p = x
	return p
}

func (x UserSignUpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserSignUpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_authentication_authentication_proto_enumTypes[0].Descriptor()
}

func (UserSignUpStatus) Type() protoreflect.EnumType {
	return &file_authentication_authentication_proto_enumTypes[0]
}

func (x UserSignUpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserSignUpStatus.Descriptor instead.
func (UserSignUpStatus) EnumDescriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

type SignUpInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignUpInput) Reset() {
	*x = SignUpInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpInput) ProtoMessage() {}

func (x *SignUpInput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpInput.ProtoReflect.Descriptor instead.
func (*SignUpInput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session         `protobuf:"bytes,1,opt,name=session,proto3,oneof" json:"session,omitempty"`
	Status  UserSignUpStatus `protobuf:"varint,2,opt,name=status,proto3,enum=authentication.UserSignUpStatus" json:"status,omitempty"`
}

func (x *SignUpOutput) Reset() {
	*x = SignUpOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpOutput) ProtoMessage() {}

func (x *SignUpOutput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpOutput.ProtoReflect.Descriptor instead.
func (*SignUpOutput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SignUpOutput) GetStatus() UserSignUpStatus {
	if x != nil {
		return x.Status
	}
	return UserSignUpStatus_SignupSignUpStatusUnknown
}

type SignInInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignInInput) Reset() {
	*x = SignInInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInput) ProtoMessage() {}

func (x *SignInInput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInput.ProtoReflect.Descriptor instead.
func (*SignInInput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *SignInInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *SignInOutput) Reset() {
	*x = SignInOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInOutput) ProtoMessage() {}

func (x *SignInOutput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInOutput.ProtoReflect.Descriptor instead.
func (*SignInOutput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *SignInOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SignOutInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *SignOutInput) Reset() {
	*x = SignOutInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignOutInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutInput) ProtoMessage() {}

func (x *SignOutInput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutInput.ProtoReflect.Descriptor instead.
func (*SignOutInput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *SignOutInput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type SignOutOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignOutOutput) Reset() {
	*x = SignOutOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignOutOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutOutput) ProtoMessage() {}

func (x *SignOutOutput) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutOutput.ProtoReflect.Descriptor instead.
func (*SignOutOutput) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{5}
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session    string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ExpireTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3,oneof" json:"expire_time,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authentication_authentication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_authentication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_authentication_authentication_proto_rawDescGZIP(), []int{6}
}

func (x *Session) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Session) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

var File_authentication_authentication_proto protoreflect.FileDescriptor

var file_authentication_authentication_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x0c,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x69,
	0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x41, 0x0a, 0x0c, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x41,
	0x0a, 0x0c, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x31,
	0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x75, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x2a, 0x92, 0x01, 0x0a, 0x10, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d,
	0x0a, 0x19, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x1d, 0x0a,
	0x19, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e,
	0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x02,
	0x12, 0x1c, 0x0a, 0x18, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x44, 0x65, 0x6e, 0x69, 0x65, 0x64, 0x10, 0x03, 0x32, 0xe8,
	0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x12, 0x1b, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x55, 0x70, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x12, 0x1b, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x1c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x4f, 0x75, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4f, 0x75,
	0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x43, 0x5a, 0x41, 0x74, 0x6f, 0x64,
	0x6f, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authentication_authentication_proto_rawDescOnce sync.Once
	file_authentication_authentication_proto_rawDescData = file_authentication_authentication_proto_rawDesc
)

func file_authentication_authentication_proto_rawDescGZIP() []byte {
	file_authentication_authentication_proto_rawDescOnce.Do(func() {
		file_authentication_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_authentication_authentication_proto_rawDescData)
	})
	return file_authentication_authentication_proto_rawDescData
}

var file_authentication_authentication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authentication_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authentication_authentication_proto_goTypes = []interface{}{
	(UserSignUpStatus)(0),         // 0: authentication.UserSignUpStatus
	(*SignUpInput)(nil),           // 1: authentication.SignUpInput
	(*SignUpOutput)(nil),          // 2: authentication.SignUpOutput
	(*SignInInput)(nil),           // 3: authentication.SignInInput
	(*SignInOutput)(nil),          // 4: authentication.SignInOutput
	(*SignOutInput)(nil),          // 5: authentication.SignOutInput
	(*SignOutOutput)(nil),         // 6: authentication.SignOutOutput
	(*Session)(nil),               // 7: authentication.Session
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_authentication_authentication_proto_depIdxs = []int32{
	7, // 0: authentication.SignUpOutput.session:type_name -> authentication.Session
	0, // 1: authentication.SignUpOutput.status:type_name -> authentication.UserSignUpStatus
	7, // 2: authentication.SignInOutput.session:type_name -> authentication.Session
	7, // 3: authentication.SignOutInput.session:type_name -> authentication.Session
	8, // 4: authentication.Session.expire_time:type_name -> google.protobuf.Timestamp
	1, // 5: authentication.Authentication.SignUp:input_type -> authentication.SignUpInput
	3, // 6: authentication.Authentication.SignIn:input_type -> authentication.SignInInput
	5, // 7: authentication.Authentication.SignOut:input_type -> authentication.SignOutInput
	2, // 8: authentication.Authentication.SignUp:output_type -> authentication.SignUpOutput
	4, // 9: authentication.Authentication.SignIn:output_type -> authentication.SignInOutput
	6, // 10: authentication.Authentication.SignOut:output_type -> authentication.SignOutOutput
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_authentication_authentication_proto_init() }
func file_authentication_authentication_proto_init() {
	if File_authentication_authentication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authentication_authentication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignOutInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignOutOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authentication_authentication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_authentication_authentication_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_authentication_authentication_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authentication_authentication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authentication_authentication_proto_goTypes,
		DependencyIndexes: file_authentication_authentication_proto_depIdxs,
		EnumInfos:         file_authentication_authentication_proto_enumTypes,
		MessageInfos:      file_authentication_authentication_proto_msgTypes,
	}.Build()
	File_authentication_authentication_proto = out.File
	file_authentication_authentication_proto_rawDesc = nil
	file_authentication_authentication_proto_goTypes = nil
	file_authentication_authentication_proto_depIdxs = nil
}
